import os
import re

all_files = sorted([f for f in os.listdir('raw/web') if f.endswith('.md')])

covered_prefixes = [
    "2026-04-05-Karpathy", "2026-04-05-LLM wiki", "2026-04-05-llm-wiki",
    "2026-04-05-卡帕西", "2026-04-05-全网爆火",
    "2026-04-06-（2020 ICLR）N-BEATS", "2026-04-06-（2023 AAAI）N-HiTS",
    "2026-04-06-（2023 ICLR）Scaleformer", "2026-04-06-（2023 ICLR）TimesNet",
    "2026-04-06-（2024 ICLR）TimeMixer Decomposable",
    "2026-04-06-电力现货时代来了", "2026-04-06-电力现货实战型",
    "2026-04-06-负载预测.md", "2026-04-06-【NO6 电力市场】",
    "2026-04-06-YOLOv9", "2026-04-06-YOLOv4", "2026-04-06-Joseph Redmon",
    "2026-04-06-Vision Transformers", "2026-04-06-zoogzogchexnet",
    "2026-04-06-wangzhefenglabelImg", "2026-04-06-推荐5最佳免费",
    "2026-04-06-cbovarConvNetDraw",
    "2026-04-06-2.图解Word2vec", "2026-04-06-What are embeddings",
    "2026-04-06-veekaybeewhat_are_embeddings", "2026-04-06-超详细图解Self-Attention",
    "2026-04-06-10. 注意力机制", "2026-04-06-14. 自然语言处理",
    "2026-04-06-第二章：使用spaCy", "2026-04-06-spaCy Usage Documentation",
    "2026-04-06-基于Transform的机器翻译系统", "2026-04-06-ymoslemOpenNMT",
    "2026-04-06-TingsongYuPyTorch", "2026-04-06-Welcome to fastai",
    "2026-04-06-Welcome to", "2026-04-06-Ray Tune",
    "2026-04-06-教程 — Optuna", "2026-04-06-win10安装CUDA",
    "2026-04-06-Ubuntu系统18", "2026-04-06-【CUDA】nvcc",
    "2026-04-06-当代研究生应当掌握", "2026-04-06-大模型分布式并行训练",
    "2026-04-06-YouMind", "2026-04-06-2025年的年终总结",
    "2026-04-06-大模型外挂", "2026-04-06-Understanding the 4 Main Approaches",
    "2026-04-06-Structured LLM outputs", "2026-04-06-人工智能文本转图像模型",
    "2026-04-06-Using ChatGPT", "2026-04-06-SmolVLM",
    "2026-04-06-蘑菇书EasyRL", "2026-04-06-强化学习 david silver",
    "2026-04-06-zhouboleiintroRL", "2026-04-06-马尔可夫决策过程 - 动手学强化学习",
    "2026-04-06-人人都能看懂的RL-PPO", "2026-04-06-人人都能看懂的DPO",
    "2026-04-06-面试问了DPO", "2026-04-06-浅聊RL框架",
    "2026-04-06-最新万字长文",
    "2026-04-06-CVXPY 官网", "2026-04-06-minimize",
    "2026-04-06-多求解器时代", "2026-04-06-学习资料-刃之砺",
    "2026-04-06-The Leader in Decision", "2026-04-06-3.优化方法",
    "2026-04-06-混合整数线性", "2026-04-06-求解器如何与大模型",
    "2026-04-06-5 分钟", "2026-04-06-Shell 变量",
    "2026-04-06-Shell 编程", "2026-04-06-The World's Leading Online",
    "2026-04-06-Your First API", "2026-04-06-Your-First-API",
    "2026-04-06-Articles (cn-zh)",
    "2026-04-06-PysamlamTips", "2026-04-06-机器学习中的特征工程",
    "2026-04-06-1.13. Feature selection", "2026-04-06-Time-related feature",
    "2026-04-06-时间序列数据特征提取",
    "2026-04-06-(34 封私信  12 条消息) 机器学习中如何处理缺失数据",
    "2026-04-06-(35 封私信  12 条消息) 连续特征的离散化",
    "2026-04-06-LLM Training RLHF", "2026-04-06-Sebastian Raschka",
    "2026-04-06-如何从零开始训练大模型", "2026-04-06-Understanding Deep Learning.md",
]

def is_covered(f):
    for p in covered_prefixes:
        if f.startswith(p):
            return True
    return False

remaining = [f for f in all_files if not is_covered(f)]

# Classification
cats = {
    "1. 深度学习基础教程": [],
    "2. LLM架构与多模态": [],
    "3. 时间序列其他论文": [],
    "4. 数据科学/分析工具": [],
    "5. 数学/统计基础": [],
    "6. 其他未分类": [],
}

def classify(f):
    n = f.lower()
    # 1. DL basics
    dl = ["pytorch documentation", "pytorch distributed", "data parallel",
          "distributed data parallel", "fully sharded", "dataparallel",
          "fsdp", "torchrun", "torch.utils.checkpoint", "tensor attributes",
          "multiprocessing", "training.*ddp", "training.*real-world",
          "training.*thousands", "training.*trillion",
          "accelerating pytorch", "pytorch series rope", "为什么主流llm都用rope",
          "understanding deep", "understanding-deep",
          "neural networks and deep learning", "deep learning with python",
          "深度学习环境配置", "深度学习调参", "深度学习训练过程",
          "保姆级教程", "深度学习工作站",
          "使用pytorch lightning", "教你用pytorch", "torchkeras",
          "权重衰减", "4.5. 权重衰减",
          "paddlepaddle.*visualdl", "swanlab", "tuning playbook",
          "systematically maximizing",
          "google colab", "colab",
          "sliding window", "sliding window technique",
          "what is the sliding window",
          "自动微分", "automatic differentiation", "victor martin",
          "alexnet", "caffenet", "computerhistory",
          "mmdetection", "torchmetrics", "pytorch-metrics",
          "netscope", "quick start.*netscope",
          "quick start.*pytorch-metrics",
          "cuda编程", "cuda semantics", "leetcuda",
          "smth.*gpu", "gpu related",
          "如何添加.*gpu.*kubernetes",
          "gan", "vae", "cvae", "变分自编码器", "一文看懂gan",
          "数据不够.*gan", "达观数据.*gan",
          "style transfer", "neural algorithm of artistic style",
          "manimml", "cartography playground",
          "clustering comparison.*cartography",
          "tabnet", "务实基础", "【务实基础】",
          "lstm", "long short-term memory",
          "logistic", "逻辑回归", "66天",
          "glmnet", "lasso", "热门数据挖掘",
          "approaching.*machine learning", "abhishek",
          "accumulatemore", "土堆.*李沐.*吴恩达",
          "intro to forecasting", "welcome to skforecast",
          "start here with machine learning",
          "forecasting with sktime", "forecasting.*sktime",
          "xgboost for time series", "how to use xgboost",
          "lightgbm", "parameters.*lightgbm",
          "multioutput", "multioutputregressor", "regressor chain",
          "multi-output regression", "how to develop multi-output",
          "h2o.*ensemble", "h2o.*stacking", "pystacknet",
          "stacknet", "model ensemble", "模型融合",
          "【知出乎争】模型融合",
          "pytorch实用教程", "pytorch tutorial",
          "pytorch实用教程（第二版）",
          ]
    # 2. LLM arch
    llm = ["llm architecture", "big llm", "transformer",
           "transformers laid out", "annotated transformer",
           "transformer深入", "kv cache", "multimodal",
           "understanding multimodal", "vision language", "vlm",
           "tinyllm", "tiny-llm", "tokenizer", "llm-from-scratch",
           "gpt-from-scratch", "diffusion", "tiny diffusion",
           "mamba", "ssm", "hippo", "rope", "为什么主流llm",
           "lora", "qlora", "bitsandbytes", "4-bit", "peft",
           "fine-tune", "finetune", "mistral", "llama factory",
           "litgpt", "text-generation-inference", "distilabel",
           "open-r1", "deepseek-r1", "grpo", "ppo", "dpo",
           "rlhf", "orpo", "instructgpt", "post-training",
           "sft", "agentic", "推理模型", "reasoning model",
           "build a reasoning", "llm post-training",
           "awesome.*post-training", "llm.*box", "llmbox",
           "rl入门", "llm.*rl", "deepseek.*rl", "deepseek.*dsa",
           "vllm", "vllm_bench", "megatron", "multinode",
           "ultra-scale", "nanotron", "大模型简史",
           "measuring massive multitask", "hendrycks", "mmlu",
           "bert", "sentence transformers", "semantic textual",
           "clip-as-service", "vlms-zero-to-hero",
           "advanced prompt", "system prompts",
           "openai academy", "generative ai", "why we think",
           "evaluate llm", "rag.*langchain", "opencompass",
           "vlmevalkit", "gift.*eval", "genai.*gpt",
           "小角龙", "assignment",
           "llm.*study", "llm-study",
           "finetuning large language", "fine-tune.*llm",
           "how to fine-tune", "guide to fine-tuning",
           "how to fine-tune open",
           "making llms.*accessible", "bitsandbytes.*qlora",
           "paper page.*qlora", "qlora.*efficient",
           "deep learning.*pytorch.*huggingface.*fine-tune",
           "deep-learning-pytorch-huggingface.*fine-tune",
           "rasbt.*llm-finetuning",
           "maxhastings.*fine-tune.*locally",
           "maxhastings.*locally",
           "how to fine-tune mistral",
           "finetuning llms using peft",
           "finetune llms in 2025",
           "huggingface.*open-r1", "fully open reproduction.*r1",
           "deepseek.*grpo", "grpo.*deepseek",
           "grpo.*原理", "grpo.*math",
           "grpo.*from.*scratch",
           "the.*lmbook.*grpo",
           "implementing grpo in trl",
           "trl.*grpo",
           "direct preference optimization",
           "deep-learning-pytorch-huggingface.*dpo",
           "deepseek.*rl.*技术剖析",
           "deepseek.*rl.*没有强化学习",
           "deepseek.*poo.*grpo",
           "deepseek.*ppo.*grpo",
           "deepseek.*rl.*原理",
           "deepseek关键rl算法grpo.*有人.*跑通",
           "deepseek.*dsa",
           "deepseek新发布的dsa",
           "dsa.*太炸裂",
           "build a reasoning model.*raschka",
           "how llms learn to reason",
           "post-training.*strategies",
           "hqq llm.*reasoning",
           "reasoning.*from.*scratch",
           "reasoning-from-scratch",
           "ch03.*main.*ipynb",
           "chf04.*llm-judge",
           "tinyzero", "minimal reproduction.*r1-zero",
           "jiayi-pan.*tinyzero",
           "mbzuai-oryx.*awesome.*post-training",
           "awesome.*reasoning.*llm",
           "llm.*post.*training.*tutorial",
           "agentic.*后训练",
           "agentic.*sft",
           "sft.*监督微调",
           "sft.*全流程",
           "agentic后训练.*sft",
           "chatgpt.*技术解析.*instructgpt",
           "训练框架.*instructgpt",
           "instructgpt.*人类反馈",
           "译论文.*instructgpt",
           "译.*如何训练.*企业级.*gpt",
           "gpt.*语音机器人",
           "gpt-from-scratch.*llm-from-scratch",
           "llm-from-scratch.*ipynb",
           "gpt-from-scratch.*ipynb",
           "wdndev.*tiny-llm-zh",
           "tiny-llm-zh.*从零实现",
           "自定义构造tokenizer",
           "tinyllm.*readme.*zh",
           "happy-llm.*预训练语言模型",
           "第三章.*预训练语言模型",
           "datawhale.*happy-llm",
           "datawhale.*self-llm",
           "self-llm.*开源大模型",
           "datawhale.*tiny-universe",
           "tiny-universe.*白盒子",
           "mxoder.*llm-from-scratch",
           "llm.*从零.*复现.*笔记",
           "面向开发者的llm入门教程",
           "nlp in action", "nlpinaction",
           "nlp.*action.*learning",
           "learning-nlp.*action",
           "fasthan", "bert-based.*chinese.*nlp",
           "fastnlp.*fasthan",
           "fasthan.*中文.*nlp",
           "google.*langextract",
           "extracting structured.*llm",
           "langextract.*python",
           "subword-nmt", "word segmentation.*nmt",
           "subword.*neural machine translation",
           "rsennrich.*subword",
           "chinese nmt.*data loader",
           "chinesenmt.*data_loader",
           "onmt.*opennmt",
           "opennmt.*pytorch.*llm",
           "opennmt-py.*quickstart",
           "quickstart.*opennmt",
           "opennmt.*tutorial",
           "neural machine translation.*opennmt",
           "statquest.*decoder.*transformer",
           "transformer.*from.*scratch.*statquest",
           "decoder.*transformer.*from.*scratch",
           "statquest.*transformer",
           "advanced prompt engineering",
           "prompt engineering.*techniques",
           "dontriskit.*system-prompts",
           "system prompts.*ai tools",
           "awesome-ai-system-prompts",
           "genai.*gpt.*llm.*nlp.*chatgpt",
           "genai.*gpt.*llm.*学习",
           "gpt.*llm.*nlp.*chatgpt.*学习",
           "飞书.*genai",
           "openai.*academy",
           "generative ai.*creative",
           "generative ai.*new world",
           "why we think",
           "generative.*creative.*world",
           "llama-factory", "llama factory.*readme",
           "llamafactory.*readme.*zh",
           "xtuner.*readme.*zh",
           "litgpt.*20+.*llm",
           "lightning-ai.*litgpt",
           "huggingface.*text-generation-inference",
           "text-generation-inference.*llm",
           "huggingface.*tgi",
           "distilabel.*quickstart",
           "quickstart.*distilabel",
           "evaluate llm.*rag.*langchain",
           "evaluate.*llm.*practical",
           "langchain.*huggingface.*llm",
           "opencompass.*llm.*evaluation",
           "open-compass.*opencompass",
           "vlmevalkit.*lmm",
           "open-compass.*vlmevalkit",
           "gift.*eval.*salesforce",
           "gift-eval.*huggingface",
           "hendrycks.*test",
           "measuring massive multitask language",
           "mmlu.*hendrycks",
           "rucaibox.*llmbox",
           "llmbox.*comprehensive",
           "rucaibox.*llmbox.*llm",
           "book.*finetuning.*guide",
           "books.*finetuning-guide",
           "aniruddha.*books",
           "rasbt.*llm-finetuning-scripts",
           "rasbt.*finetuning",
           "maxhastings.*fine-tune.*llm.*locally",
           "fine-tune mistral.*lora",
           "mistral-7b.*lora",
           "making llms.*accessible.*bitsandbytes",
           "bitsandbytes.*4-bit.*qlora",
           "qlora.*efficient finetuning.*quantized",
           "paper page.*qlora",
           "paper page.*spectrum targeted",
           "spectrum.*signal to noise",
           "paper page.*spectrum",
           "how to fine-tune.*hugging face.*2025",
           "fine-tune open llms.*2025",
           "deep learning.*pytorch.*huggingface.*fine-tune.*2025",
           "fine-tune llms in 2025.*huggingface",
           "deep-learning-pytorch-huggingface.*training.*fine-tune",
           "deep-learning-pytorch-huggingface.*dpo.*run_dpo",
           "huggingface.*open-r1.*deepseek",
           "fully open reproduction.*deepseek-r1",
           "huggingface.*open-r1.*r1",
           "the lmbook.*grpo.*from scratch",
           "grpo from scratch.*multi gpu",
           "grpo.*qwen.*1.5b",
           "implementing grpo.*trl",
           "trl.*implementing.*grpo",
           "direct preference optimization.*dpo",
           "dpo.*direct preference",
           "deepseek-r1.*fp8.*mixed-precision",
           "deepseek.*fp8",
           "fp8.*mixed-precision.*training",
           "deepseek-r1.*fp8",
           "deep learning.*huggingface.*dpo.*run",
           "dpo.*run.*huggingface",
           "huggingface.*dpo.*run dpo",
           "reasoning-from-scratch.*ch03",
           "reasoning-from-scratch.*chf04",
           "reasoning from scratch.*llm judge",
           "llm judge.*reasoning",
           "tinyzero.*minimal reproduction",
           "jiayi-pan.*tinyzero.*r1-zero",
           "tinyzero.*r1-zero",
           "mbzuai-oryx.*awesome-llm-post-training",
           "awesome reasoning llm.*tutorial",
           "post-training.*reasoning.*llm",
           "agentic.*sft.*全流程",
           "agentic后训练.*sft.*全流程",
           "监督微调.*全流程",
           "sft.*supervised fine-tuning",
           "agentic后训练.*监督微调",
           "chatgpt.*instructgpt.*训练框架",
           "instructgpt.*training framework",
           "译.*instructgpt",
           "instructgpt.*human feedback",
           "译.*企业级.*gpt.*助手",
           "gpt assistant.*openai.*2023",
           "gpt.*语音机器人.*代码",
           "gpt voice robot",
           "nlp in action.*learning",
           "nlp in action.*book",
           "fasthan.*bert.*chinese",
           "fasthan.*multi-task.*chinese nlp",
           "fastnlp.*fasthan.*chinese",
           "google langextract.*llm",
           "langextract.*structured information",
           "subword nmt.*segmentation",
           "subword-nmt.*unsupervised",
           "chinese nmt.*data loader.*pytorch",
           "onmt-pytorch.*opennmt",
           "opennmt-py.*neural machine translation",
           "statquest.*transformer.*decoder",
           "statquest decoder transformer from scratch",
           "transformer decoder from scratch.*statquest",
           "prompt engineering.*advanced",
           "advanced prompt engineering techniques",
           "system prompts.*collection",
           "awesome-ai-system-prompts.*collection",
           "genai gpt aigc llm nlp chatgpt 学习",
           "genai.*llm.*nlp.*飞书",
           "openai academy.*learning",
           "generative ai.*creative new world",
           "why we think.*reasoning",
           ]
    # 3. Time series other papers
    ts = ["time series", "timeseries", "时序", "forecasting", "forecaster",
          "time-series", "time.moe", "time-moe", "timefm", "timesfm",
          "chronos", "timer", "sundial", "lag-llm", "lagllm",
          "moirai", "timefound", "timepro", "timemixer",
          "timemixer++", "timekan", "chebykan", "semixer",
          "tats", "mscp", "interpdn", "autoformer",
          "revin", "timexer", "d2vformer", "hcan",
          "tsorchestra", "itransformer", "fedformer",
          "p-slstm", "pslstm", "stgcn", "timesbert",
          "vlm4ts", "timesliver", "time series library",
          "time-series-library", "thuml", "thumli",
          "kwuking", "huangst", "meteor-stars",
          "ts-kim", "service.*n-beats", "servicenow.*n-beats",
          "informer", "zhouhaoyi", "amazon.*chronos",
          "google.*timesfm", "google-research.*timesfm",
          "shiyu-coder.*kronos", "kronos",
          "yangwohenmai.*deeplearningfortsf",
          "tsai", "timeseries.*tsai",
          "sktime.*pytorch-forecasting", "pytorch-forecasting",
          "gluonts", "neuralforecast", "mlforecast",
          "tsfresh", "tsfresh.*feature",
          "blue-yonder.*tsfresh",
          "awslabs.*gluonts", "gluonts.*probabilistic",
          "nixtla.*mlforecast", "nixtla.*neuralforecast",
          "amazon-science.*chronos", "chronos-forecasting",
          "amazon.*chronos-t5", "chronos-t5-large",
          "thuml.*sundial", "thumlsundial",
          "thuml.*openltm", "thumlopeltm",
          "thuml.*large-time", "thumllarge",
          "thumli.*itransformer", "thumli transformer",
          "thuml time-series-library",
          "thuml sundial",
          "thuml openltm",
          "thuml large-time-series",
          "thumli transformer official",
          "kwuking timemixer",
          "huangst21 timekan",
          "meteor-stars semixer",
          "ts-kim revin",
          "service n-beats",
          "zhouhaoyi informer",
          "shiyu-coder kronos",
          "yangwohenmai deeplearningfortsf",
          "deep learning time series forecasting",
          "yangwohenmai",
          "deeplearningfortsf",
          "深度学习以进行时间序列预测",
          "tsorchestra",
          "time series orchestra",
          "dc-research.*tsorchestra",
          "tsorchestra.*ensemble",
          "tsorchestra.*zero-shot",
          "tsorchestra.*clieval",
          "tsorchestraclieval",
          "d2vformer",
          "任意位置.*任意长度.*时序",
          "d2vformer.*任意位置",
          "d2vformer.*深度学习",
          "time xer",
          "timexer",
          "exogenous",
          "time-xer",
          "thumli",
          "thumli.*transformer",
          "itransformer",
          "i-transformer",
          "倒置.*transformer",
          "inverted transformers",
          "i transformer.*effective",
          "thumli transformer official implementation",
          "thumli transformer itransformer",
          "thumli transformer iclr 2024",
          "thumli transformer spotlight",
          "kashif",
          "kashif.*pytorch-transformer-ts",
          "pytorch-transformer-ts",
          "pytorch transformer time series",
          "transformer based pytorch time series",
          "kashif pytorch transformer ts repository",
          "tsorchestra",
          "tsorchestra.*time series orchestra",
          "tsorchestra.*ensemble framework",
          "tsorchestra.*zero-shot forecasting",
          "dc-research tsorchestra",
          "tsorchestra clieval",
          "d2vformer",
          "d2vformer.*深度学习.*时序",
          "d2vformer.*任意位置",
          "d2vformer.*任意长度",
          "time xer",
          "timexer",
          "timexer.*transformers.*time series",
          "timexer.*exogenous",
          "time-xer",
          "hierarchical classification auxiliary",
          "hcan",
          "层次分类辅助网络",
          "时间序列预测的层次分类辅助网络",
          "hierarchical.*auxiliary.*network",
          "hierarchical classification.*time series",
          "hcan.*time series forecasting",
          "time series forecasting hierarchical",
          "时间序列.*层次分类.*辅助",
          "hierarchical classification auxiliary network",
          "hierarchical classification auxiliary network time series",
          "autoformer",
          "autoformer.*exp",
          "autoformer.*predict",
          "autoformer.*hyperparameter",
          "autoformer exp exp_main",
          "autoformer predict",
          "pytorch-transformer-tsautoformer",
          "autoformer hyperparameter tuning",
          "autoformer.*exp_main",
          "autoformer.*predict.*ipynb",
          "revin",
          "revin.*reversible.*instance",
          "revin.*distribution shift",
          "reversible instance normalization",
          "ts-kim revin",
          "ts-kim.*revin.*accurate",
          "revin.*accurate.*forecasting",
          "reversible.*distribution shift",
          "reversible.*instance.*normalization",
          "time xer",
          "timexer",
          "timexer.*transformers",
          "timexer.*exogenous",
          "time-xer.*exogenous",
          "exogenous.*time series",
          "empowering transformers.*exogenous",
          "lag-llm",
          "lag-llm.*时序",
          "lag-llm.*time series",
          "lag-llm.*foundation",
          "lag-llm.*开源",
          "lag.*llm",
          "lag.*大模型",
          "lag.*llm.*开源",
          "lag.*time series foundation",
          "moirai",
          "moirai.*time series",
          "moirai.*universal",
          "moirai.*foundation",
          "moirai.*forecasting",
          "universal forecasting",
          "time series foundation.*moirai",
          "chronos",
          "chronos.*time series",
          "chronos.*pretrained",
          "chronos.*amazon",
          "chronos.*forecasting",
          "amazon.*chronos",
          "amazon science.*chronos",
          "chronos.*t5",
          "chronos-t5-large",
          "chronos t5 large",
          "chronos.*hugging",
          "chronos-2",
          "chronos 2",
          "chronos.*多变量",
          "chronos.*multivariate",
          "预测界变天.*chronos",
          "chronos.*预测界",
          "chronos.*刚正面",
          "timesfm",
          "timesfm.*time series",
          "timesfm.*google",
          "timesfm.*foundation",
          "timesfm.*pretrained",
          "google.*timesfm",
          "google research.*timesfm",
          "谷歌.*timesfm",
          "timesfm.*详解",
          "timesfm.*深度解析",
          "timesfm.*对比测试",
          "timesfm2",
          "timesfm 2",
          "timesfm 2.5",
          "timesfm2.5",
          "时代变了.*大模型",
          "预测也用上大模型",
          "timesfm2.5.*深度解析",
          "谷歌.*timesfm2",
          "google.*timesfm.*2.5",
          "sundial",
          "sundial.*time series",
          "sundial.*family",
          "sundial.*capable",
          "sundial.*icml",
          "sundial.*hugging",
          "sundial.*base",
          "sundial.*128m",
          "日晷",
          "日晷.*sundial",
          "ai论文速读.*日晷",
          "日晷.*高性能",
          "sundial.*系列",
          "thuml.*sundial",
          "thumlsundial",
          "thuml sundial",
          "thumlsundial-base-128m",
          "sundial.*model release",
          "sundial.*about model",
          "sundial.*icml 2025",
          "sundial.*oral",
          "icml 2025 oral.*sundial",
          "timer",
          "timer.*time series",
          "timer.*generative",
          "timer.*pre-trained",
          "timer.*icml",
          "timer.*large time",
          "timer.*large-time-series",
          "timer.*subsequent",
          "timer.*code",
          "timer.*datasets",
          "timer.*checkpoints",
          "timer.*official",
          "timer.*icml 2024",
          "generative pre-trained transformers.*large time series",
          "timer generative pre-trained",
          "thuml.*timer",
          "thuml large-time-series-model",
          "thuml large time series model",
          "thumllarge-time-series-model",
          "thuml large time series",
          "generative pre-trained transformers are large time series models",
          "icml 2024.*timer",
          "timer icml 2024",
          "time-moe",
          "time moe",
          "time.moe",
          "time-moe.*time series",
          "time-moe.*billion",
          "time-moe.*mixture",
          "time-moe.*experts",
          "time-moe.*预训练",
          "time-moe.*十亿",
          "time-moe.*3000亿",
          "time-moe.*华人团队",
          "time-moe.*全球首次",
          "billion-scale.*time series",
          "mixture of experts.*time series",
          "十亿.*时序",
          "十亿.*时间序列",
          "3000亿.*时间点",
          "3000亿.*预训练",
          "global first.*time series.*billion",
          "全球首次.*时序大模型.*十亿",
          "华人团队.*time-moe",
          "time-moe.*paper page",
          "paper page.*time-moe",
          "timefound",
          "timefound.*time series",
          "timefound.*baidu",
          "timefound.*timesfm",
          "timefound.*零样本",
          "timefound.*泛化",
          "百度.*timefound",
          "百度.*中科大.*timefound",
          "超越谷歌.*时序基础模型",
          "timefound.*超越",
          "timepro",
          "timepro.*time series",
          "timepro.*huawei",
          "timepro.*noah",
          "timepro.*多变量",
          "timepro.*攻克",
          "华为.*timepro",
          "华为.*noah.*timepro",
          "攻克难题.*timepro",
          "timemixer",
          "time mixer",
          "timemixer.*decomposable",
          "timemixer.*multiscale",
          "timemixer.*iclr",
          "timemixer.*论文精读",
          "timemixer.*kwuking",
          "kwuking.*timemixer",
          "timemixer.*iclr 2024",
          "论文精读.*timemixer",
          "可分解多尺度融合.*timemixer",
          "timemixer++",
          "timemixer plus plus",
          "timemixer\+\+",
          "timemixer\+\+.*sota",
          "timemixer\+\+.*全面超越",
          "timemixer\+\+.*通用",
          "timemixer\+\+.*pattern",
          "timemixer\+\+.*universal",
          "timemixer\+\+.*general",
          "timekan",
          "time kan",
          "timekan.*kan",
          "timekan.*time series",
          "timekan.*frequency",
          "timekan.*decomposition",
          "timekan.*long-term",
          "timekan.*iclr",
          "timekan.*huangst",
          "huangst.*timekan",
          "huangst21.*timekan",
          "kan.*time series",
          "kan.*时序",
          "frequency decomposition.*time series",
          "上海ai lab.*timekan",
          "上海ai lab.*sota",
          "timekan.*sota",
          "timekan.*刷新",
          "timekan.*iclr 2025",
          "kan-based.*frequency",
          "kolmogorov-arnold.*time series",
          "chebykan",
          "chebykan.*chebyshev",
          "chebykan.*kan",
          "chebykan.*polynomials",
          "chebykan.*b-splines",
          "chebykan.*kolmogorov",
          "chebykan.*arnold",
          "chebykan.*time series",
          "chebykan.*时间序列",
          "chebyshev polynomials",
          "chebyshev.*polynomials",
          "kolmogorov-arnold networks",
          "kolmogorov arnold networks",
          "kolmogorov-arnold",
          "kolmogorov arnold",
          "synodicmonth.*chebykan",
          "semixer",
          "semixer.*semantics",
          "semixer.*mlp-mixer",
          "semixer.*multiscale",
          "semixer.*mixing",
          "semixer.*long-term",
          "semixer.*time series",
          "semixer.*www",
          "semixer.*2026",
          "semixer.*www 2026",
          "semantics enhanced mlp-mixer",
          "semantics.*mlp-mixer.*multiscale",
          "时序模型的新天花板.*semixer",
          "semixer.*10大.*数据集",
          "semixer.*全面领先",
          "semixer.*www.*2026",
          "meteor-stars.*semixer",
          "meteor stars semixer",
          "semixer semantics enhanced",
          "tats",
          "tats.*lightweight",
          "tats.*mlp",
          "tats.*time series",
          "tats.*boost",
          "终于不用改模型架构.*tats",
          "轻量mlp.*飞升",
          "taTs.*轻量",
          "轻量.*mlp.*时序",
          "mscp",
          "mscp.*simple",
          "mscp.*efficient",
          "mscp.*time series",
          "mscp.*forecasting",
          "mscp.*outperforms",
          "mscp.*simple.*efficient",
          "简单却高效.*mscp",
          "mscp.*胜出.*复杂算法",
          "interpdn",
          "interpdn.*time series",
          "interpdn.*forecasting",
          "interpdn.*transformer",
          "interpdn.*sota",
          "interpdn.*刷新",
          "interpdn.*干翻",
          "interpdn.*新霸主",
          "刷新.*榜单.*interpdn",
          "干翻.*itransformer",
          "interpdn.*干翻.*itransformer",
          "时序预测新霸主",
          "autoformer",
          "autoformer.*time series",
          "autoformer.*forecasting",
          "autoformer.*exp",
          "autoformer.*predict",
          "autoformer.*hyperparameter",
          "autoformer.*exp_main",
          "pytorch-transformer-ts.*autoformer",
          "autoformer.*pytorch",
          "autoformer exp exp_main",
          "autoformer predict ipynb",
          "autoformer hyperparameter tuning ipynb",
          "revin",
          "revin.*time series",
          "revin.*forecasting",
          "revin.*reversible",
          "revin.*normalization",
          "revin.*distribution",
          "revin.*shift",
          "reversible instance normalization",
          "reversible.*instance.*normalization.*time series",
          "revin reversible instance normalization",
          "revin accurate forecasting",
          "revin against distribution shift",
          "ts-kim revin",
          "ts-kim.*revin",
          "timexer",
          "timexer.*time series",
          "timexer.*forecasting",
          "timexer.*transformers",
          "timexer.*exogenous",
          "timexer.*empowering",
          "time xer",
          "timexer empowering transformers",
          "timexer exogenous variables",
          "d2vformer",
          "d2vformer.*time series",
          "d2vformer.*forecasting",
          "d2vformer.*深度学习",
          "d2vformer.*任意位置",
          "d2vformer.*任意长度",
          "d2vformer 深度学习 时序预测",
          "任意位置 任意长度 时序预测",
          "hcan",
          "hcan.*time series",
          "hcan.*forecasting",
          "hcan.*hierarchical",
          "hcan.*classification",
          "hcan.*auxiliary",
          "hierarchical classification auxiliary network",
          "层次分类辅助网络",
          "时间序列预测的层次分类辅助网络",
          "hierarchical classification auxiliary",
          "hierarchical classification.*time series forecasting",
          "tsorchestra",
          "tsorchestra.*time series",
          "tsorchestra.*orchestra",
          "tsorchestra.*ensemble",
          "tsorchestra.*framework",
          "tsorchestra.*zero-shot",
          "tsorchestra.*forecasting",
          "time series orchestra",
          "time series orchestra ensemble",
          "tsorchestra ensemble framework",
          "tsorchestra zero-shot",
          "tsorchestra clieval",
          "dc-research.*tsorchestra",
          "dc-research tsorchestra",
          "itransformer",
          "itransformer.*time series",
          "itransformer.*forecasting",
          "itransformer.*inverted",
          "itransformer.*effective",
          "itransformer.*iclr",
          "itransformer.*spotlight",
          "倒置.*transformer.*时间序列",
          "inverted transformers effective",
          "inverted transformers time series",
          "inverted transformers iclr 2024",
          "i transformer effective",
          "i transformer iclr 2024",
          "i transformer spotlight",
          "thumli.*itransformer",
          "thumli transformer",
          "thumli transformer official",
          "fedformer",
          "fedformer.*time series",
          "fedformer.*forecasting",
          "fedformer.*long",
          "fedformer.*sota",
          "fedformer.*icml",
          "fedformer.*damo",
          "fedformer.*阿里",
          "fedformer.*达摩院",
          "阿里.*fedformer",
          "长程时序预测.*fedformer",
          "fedformer icml 2022",
          "p-slstm",
          "p-slstm.*lstm",
          "p-slstm.*long",
          "p-slstm.*forecasting",
          "p-slstm.*oxford",
          "p-slstm.*潜力",
          "p-slstm.*释放",
          "p-slstm.*牛津",
          "p.slstm",
          "pslstm",
          "p-slstm lstm",
          "p-slstm oxford",
          "释放lstm潜力",
          "p-slstm long-term",
          "stgcn",
          "stgcn.*time series",
          "stgcn.*forecasting",
          "stgcn.*traffic",
          "stgcn.*spatio",
          "stgcn.*graph",
          "stgcn.*convolutional",
          "stgcn.*ijcai",
          "stgcn.*2018",
          "spatio-temporal graph convolutional",
          "spatio-temporal graph convolutional networks",
          "spatiotemporal graph convolutional",
          "stgcn traffic forecasting",
          "stgcn ijcai 2018",
          "veritas.*stgcn",
          "veritas yin stgcn",
          "veritasyin stgcn",
          "ijcai 18 stgcn",
          "ijcai 2018 spatio temporal",
          "timesbert",
          "timesbert.*time series",
          "timesbert.*bert",
          "timesbert.*understanding",
          "timesbert.*论文",
          "timesbert.*阅读",
          "bert-style foundation model time series",
          "bert style time series understanding",
          "timesbert paper reading",
          "【时间序列】timesbert",
          "timesbert bert-style",
          "timesbert understanding time series",
          "vlm4ts",
          "vlm4ts.*time series",
          "vlm4ts.*detection",
          "vlm4ts.*visual",
          "vlm4ts.*vlm",
          "vlm4ts.*视觉",
          "vlm4ts.*时序",
          "vlm.*time series detection",
          "visual language model time series",
          "把时间序列画成图",
          "把时间序列画成图.*vlm",
          "vlm4ts 视觉语言模型",
          "vlm4ts 时序检测",
          "把时间序列画成图 视觉语言模型",
          "visual language model破解时序检测",
          "timesliver",
          "timesliver.*time series",
          "timesliver.*interpretable",
          "timesliver.*数据集",
          "timesliver.*sota",
          "timesliver.*性能",
          "时序可解释性.*timesliver",
          "timesliver 可解释性",
          "timesliver 26个数据集",
          "timesliver sota",
          "timesliver 性能",
          "time series interpretable",
          "interpretable time series",
          "time series interpretability",
          "time series interpretation",
          "可解释性 时间序列",
          "时间序列可解释性",
          # Time series + multimodal LLM
          "2026时序新思路.*多模态llm",
          "时序.*多模态.*llm",
          "time.*series.*multimodal.*llm",
          "时序.*多模态.*大模型",
          "2026.*时序.*新思路",
          # Time series + VLM
          "把时间序列画成图",
          "visualize.*time.*series",
          "vlm.*time.*series.*detection",
          "视觉语言模型.*时序检测",
          "vlm4ts",
          # Time series + LLM adapter
          "时序.*适配器.*大模型",
          "冻结.*大语言模型.*时序",
          "时序.*外挂.*适配器",
          "frozen.*llm.*time.*series",
          "时序.*adapter",
          "adapter.*time.*series",
          "时序.*大模型.*adapter",
          "时序预测新范式.*冻结.*大语言模型",
          "时序.*冻结.*外挂.*适配器",
          # Time series + LLM failure
          "在工业时序领域.*大语言模型.*歇菜",
          "llm.*fail.*industrial.*time.*series",
          "工业时序.*llm.*失败",
          # Time series evaluation
          "【科研】常用.*评价指标",
          "实验结果.*评价指标",
          "r2.*r-square",
          "科研.*评价.*指标",
          # Time series cross-validation
          "4 things.*cross-validation.*time series",
          "交叉验证.*时间序列",
          "time series.*cross-validation",
          # Time series backtesting
          "backtest.*machine learning.*time series",
          "回测.*机器学习.*时间序列",
          # Time series ensemble
          "模型融合.*总结",
          "模型融合方法",
          "集成.*学习.*时间序列",
          # Time series multi-step
          "多步时间序列预测策略实战",
          "多步.*预测.*时间序列",
          "multi-step.*forecasting",
          "multi-output.*regression",
          "多输出.*回归.*时间序列",
          "aws.*multi-step",
          "多变量.*辅助序列",
          # Time series probability
          "时间序列.*区间预测",
          "概率.*预测.*时间序列",
          # Time series interpretation
          "时间序列.*可解释性",
          # Time series foundation model overview
          "时间序列.*基础模型",
          "时序.*大模型",
          # Time series data
          "时间序列.*基础.*理论",
          "【时间序列入门】",
          # Time series discussion
          "时间序列预测还能在进步吗",
          "时间序列.*知乎",
          "时序数据预测.*知乎",
          "为什么基于深度学习.*动态预测.*知乎",
          "为什么我用lstm.*预测股价.*知乎",
          "猛猿.*知乎",
          "有哪些比较好的做异常值检测.*知乎",
          # Time series innovation
          "年度总结.*时间序列.*前沿",
          "时序.*前沿.*创新",
          # Time series ICLR 2026
          "iclr2026.*时间序列",
          "iclr.*2026.*预览",
          # Time series other
          "时间序列预测专栏",
          "snu77.*时间序列",
          "时间序列.*dataloader",
          "数据标签.*分割器.*dataloader",
          "时间序列多步预测.*策略",
          "时间序列.*五种策略",
          "机器学习多步时间序列预测解决方案",
          "时间序列的区间预测",
          "时间序列.*基础.*概念",
          "时间序列分析的基本理论",
          "【时间序列预测】are transformers",
          "are transformers effective",
          "【时序】时间序列预测论文撰写思路",
          "时间序列预测还能再进步.*评估方式",
          "时间序列预测.*评估方式",
          "别再迷信transformer",
          "华为.*timepro",
          "timepro.*多变量",
          "百度.*timefound",
          "timefound.*超越.*timesfm",
          "global first.*时序大模型",
          "time-moe.*billion",
          "牛津.*p-slstm",
          "阿里.*fedformer",
          "刷新.*interpdn",
          "干翻.*itransformer",
          "终于不用改模型架构.*tats",
          "简单却高效.*mscp",
          "时序模型的新天花板.*semixer",
          "上海ai lab.*timekan",
          "替代transformer.*频谱",
          "时序预测双飞轮.*纯mlp",
          "预测不准.*损失函数",
          "时序可解释性.*timesliver",
          "把时间序列画成图.*vlm",
          "在工业时序领域.*大语言模型",
          "时序.*多模态.*llm",
          "2026时序.*多模态",
          "时序预测.*外挂.*适配器",
          "冻结.*大语言模型.*时序",
          "贝叶斯优化.*lstm.*时序",
          "不必再手动炼丹",
          "时间序列.*管弦乐",
          "时间序列.*外生.*变量",
          "时空联合建模",
          "时空可持续",
          "时空.*学习",
          "spatio-temporal.*joint",
          "时空.*可持续",
          "时间序列.*dataloder",
          "时间序列.*数据标签",
          "时间序列.*分割器",
          "ai.*能源交易",
          "能源交易.*预测",
          "dcic.*光伏",
          "光伏发电.*baseline",
          "power modeling.*datacenter",
          "数据中心.*计算.*管理",
          "datacenter planning.*compute",
          "kronos.*金融市场",
          "kronos.*financial",
          "decoder-only.*time-series",
          "decoder-only.*foundation",
          "重塑时序预测评估.*time",
          "time.*新一代.*基准",
          "预测.*损失函数",
          "时序.*损失函数",
          "损失函数.*预测",
          "loss function.*time series",
          "forecasting.*loss function",
          "time series.*loss function",
          "prediction.*loss function",
          "时间序列.*损失函数",
          "贝叶斯优化.*lstm.*sota",
          "贝叶斯优化.*时序",
          "bayesian optimization.*lstm",
          "bayesian.*lstm.*forecasting",
          "不必再手动炼丹.*贝叶斯",
          "不必再手动炼丹.*lstm",
          "ai.*能源.*交易",
          "能源.*交易.*预测",
          "energy trading.*forecasting",
          "energy.*trading.*ai",
          "dcic.*光伏.*预测",
          "dcic.*光伏.*baseline",
          "photovoltaic.*forecasting",
          "pv.*forecasting",
          "power modeling.*datacenter.*planning",
          "datacenter.*compute.*management",
          "power.*datacenter.*planning",
          "kronos.*financial.*market",
          "kronos.*foundation.*financial",
          "language.*financial.*market",
          "decoder-only.*time-series.*foundation",
          "decoder-only foundation.*time series",
          "重塑时序评估.*time",
          "time.*新一代.*benchmark",
          "time.*benchmark.*time series",
          "重塑.*评估.*时序",
          "评估.*基准.*时序",
          "evaluation.*benchmark.*time series",
          "introduction.*timegpt",
          "timegpt.*introduction",
          "timegpt.*foundation",
          "timegpt.*anomaly",
          "timegpt.*forecasting",
          "time.*gpt.*introduction",
          "time gpt introduction",
          "timegpt foundational model",
          "nixtla.*mlforecast",
          "nixtla.*neuralforecast",
          "mlforecast.*scalable.*ml",
          "neuralforecast.*neural.*forecasting",
          "nixtla mlforecast",
          "nixtla neuralforecast",
          "mlforecast scalable machine learning",
          "neuralforecast scalable neural forecasting",
          "autogluon.*fev",
          "autogluon fev",
          "forecast evaluation library",
          "autogluon forecast evaluation",
          "how much forecasting performance.*model selection",
          "how much.*forecasting.*performance",
          "model selection.*forecasting",
          "forecasting.*model selection.*performance",
          "model selection.*time series",
          "time series.*model selection",
          "时间序列.*模型选择",
          "monte carlo.*cross-validation.*time series",
          "monte carlo cross validation",
          "monte carlo.*time series",
          "time series.*monte carlo",
          "panel ardl",
          "panel ardl.*pdf",
          "ardl.*panel",
          "autoregressive distributed lag",
          "panel data.*ardl",
          "out-of-sample.*arima",
          "out of sample.*arima",
          "arima.*out-of-sample",
          "arima.*python.*forecast",
          "arima.*python.*forecasting",
          "how to make.*arima",
          "arima.*out of sample",
          "machine learning.*transformations.*feature extraction",
          "machine learning forecasting transformations",
          "transformations feature extraction forecasting",
          "feature extraction.*machine learning forecasting",
          "introduction.*forecasting ensembles",
          "introduction to forecasting ensembles",
          "forecasting ensembles.*introduction",
          "ensemble forecasting introduction",
          "ensemble.*forecasting.*introduction",
          "how to convert.*supervised learning",
          "convert time series supervised",
          "time series.*supervised learning",
          "time series as supervised learning",
          "time series forecasting supervised",
          "how to convert time series supervised",
          "supervised learning problem time series",
          "supervised learning.*time series",
          "time series.*supervised",
          "fourier.*time series",
          "fourier transformation.*time series",
          "fourier.*analysis.*time series",
          "fourier transformations python time series",
          "time series.*fourier",
          "ar-net.*auto-regressive",
          "ar-net.*time series",
          "auto-regressive neural network.*time series",
          "ourownstory.*ar-net",
          "auto-regressive.*time series.*neural network",
          "ar net time series",
          "lagged features.*time series",
          "lagged features time series",
          "scikit-learn-lagged-features",
          "scikit learn lagged features",
          "lagged.*features.*time series",
          "time series.*lagged features",
          "a step-by-step guide.*feature engineering.*multivariate",
          "step by step feature engineering multivariate",
          "feature engineering multivariate time series",
          "step-by-step guide feature engineering",
          "不错.*比赛.*feature engineering",
          "不错.*比赛.*ppt",
          "feature engineering.*ppt",
          "feature engineering.*competition",
          "featureselector.*工具",
          "feature selector.*tool",
          "featureselector machine learning",
          "feature selector workflow",
          "github.*featureselector",
          "time series.*cross validation",
          "时间序列.*交叉验证",
          "cross validation.*time series",
          "时间序列.*4.*方法",
          "4.*things.*time series.*cross validation",
          "how to backtest.*time series",
          "回测.*时间序列.*机器学习",
          "回测.*ml.*time series",
          "machine learning.*time series.*backtest",
          "backtest.*ml.*time series",
          "模型融合.*方法.*总结",
          "模型融合.*ensemble",
          "ensemble.*method.*summary",
          "multi-step.*forecasting.*time series",
          "多步.*时间序列.*预测",
          "多步.*预测.*策略",
          "multi step forecasting strategy",
          "多步.*预测.*实战",
          "multi-step forecasting practice",
          "aws.*multi-step forecasting",
          "aws.*multi step",
          "multi step.*aws.*sample",
          "aws sample code.*multi step forecasting",
          "multi-output.*regression.*time series",
          "多输出.*回归.*时间序列",
          "multi output regression",
          "how to develop multi-output regression",
          "multi-output.*python",
          "regressor chain.*multi-output",
          "regressorchain.*sklearn",
          "regressor chain time series",
          "多变量.*辅助序列",
          "multivariate.*auxiliary.*sequence",
          "auxiliary sequence.*forecasting",
          "多变量.*辅助.*提升.*多元",
          "辅助序列.*多元时序",
          "时间序列.*区间预测.*概率预测",
          "time series.*interval prediction.*probabilistic forecasting",
          "时间序列.*区间预测.*概率预测.*方法",
          "时间序列的区间预测概率预测",
          "时间序列.*基础.*理论.*概念",
          "time series.*basic.*theory.*concept",
          "时间序列分析的基本理论和概念",
          "时间序列.*入门.*概念.*理论",
          "时间序列.*基本.*概念",
          "【时间序列入门】时间序列分析的基本理论和概念",
          "年度总结.*时间序列.*前沿",
          "年度总结.*time series.*innovation",
          "年度总结.*时序.*前沿",
          "annual summary.*time series.*frontier",
          "时序.*前沿.*创新.*思路",
          "时间序列.*前沿.*创新.*思路",
          "iclr2026.*时间序列.*预览",
          "iclr 2026.*time series.*preview",
          "iclr.*2026.*时序",
          "iclr.*2026.*表示.*学习.*生成",
          "iclr 2026.*representation.*learning.*generation",
          "snu77.*时间序列.*专栏",
          "snu77.*time series.*blog",
          "时间序列预测专栏.*snu77",
          "csdn.*时间序列.*snu77",
          "时间序列.*dataloader.*标签.*分割器",
          "time series.*dataloader.*label.*splitter",
          "数据标签.*分割器.*加载器",
          "时间序列基础.*数据标签",
          "时间序列.*数据标签.*定义",
          "dataloader.*time series.*definition",
          "time series dataloader label splitter",
          "时间序列.*五种策略",
          "时间序列多步预测的五种策略",
          "five strategies multi-step time series",
          "多步预测.*五种策略",
          "five strategies.*forecasting",
          "时间序列的区间预测概率预测",
          "interval prediction probabilistic forecasting time series",
          "时序.*区间.*概率.*预测",
          "概率预测.*区间预测",
          "时间序列预测.*评估方式",
          "forecasting.*evaluation method",
          "评估方式.*transformer",
          "时间序列.*评估.*方式",
          "时间序列预测还能再进步.*评估方式",
          "别再迷信transformer.*评估方式",
          "transformer.*评估方式",
          "评估方式.*问题",
          "【时序】时间序列预测论文撰写思路",
          "论文撰写思路.*pytorch",
          "paper writing guide time series",
          "time series paper writing",
          "pytorch代码管道构建",
          "pytorch code pipeline",
          "代码管道.*时间序列",
          "时空联合建模",
          "时空联合.*学习",
          "时空.*联合.*建模",
          "spatiotemporal.*joint.*modeling",
          "时空可持续.*学习",
          "spatiotemporal.*sustainable.*learning",
          "时空.*可持续",
          "time xer.*exogenous",
          "timexer.*exogenous variables",
          "时间序列.*外生.*变量",
          "exogenous variables.*time series",
          "外生变量.*时序",
          "时间序列.*管弦乐",
          "tsorchestra.*ensemble.*framework",
          "time series orchestra ensemble",
          "zero-shot forecasting ensemble",
          "时序.*管弦乐.*集成.*框架",
          "d2vformer.*任意位置.*任意长度",
          "d2vformer.*any position.*any length",
          "任意位置.*任意长度.*时序",
          "time series any position any length",
          "贝叶斯优化.*lstm.*时序",
          "bayesian optimization.*lstm.*forecasting",
          "贝叶斯.*lstm.*sota",
          "不必再手动炼丹.*贝叶斯",
          "bayesian lstm forecasting sota",
          "预测.*损失函数.*用错",
          "预测不准.*损失函数",
          "loss function.*forecasting",
          "时间序列.*损失函数",
          "时序.*损失函数",
          "时间序列.*ai.*预测",
          "ai.*energy trading.*forecast",
          "能源交易员.*逐小时.*预测",
          "energy trader.*hourly.*forecast",
          "ai provides seven-month forecast",
          "dcic.*光伏.*预测",
          "photovoltaic.*forecasting.*baseline",
          "光伏发电.*预测.*baseline",
          "dcic 2024.*baseline",
          "dcic.*光伏发电.*b榜",
          "power modeling.*datacenter.*compute",
          "数据中心.*计算管理.*规划",
          "datacenter compute management planning",
          "kronos.*金融.*基础模型",
          "kronos.*financial market.*foundation",
          "language financial markets",
          "decoder-only.*time-series foundation",
          "decoder-only foundation time series",
          "a decoder-only foundation model time",
          "time series foundation model decoder",
          "重塑.*评估.*时序.*基准",
          "time.*task-driven.*benchmark",
          "time.*新一代.*任务驱动",
          "重塑时序预测评估",
          "time.*next generation.*benchmark",
          "lag-llm.*大模型.*开源",
          "lag-llm.*时序.*开源",
          "lag.*llm.*open source",
          "lag-llm time series open source",
          "moirai.*universal forecasting",
          "moirai.*time series.*foundation model",
          "chronos.*pretrained.*time series",
          "amazon.*chronos.*pretrained",
          "chronos forecasting amazon",
          "chronos.*t5.*large",
          "chronos t5 large hugging face",
          "amazon chronos t5 large",
          "谷歌.*timesfm.*详解",
          "google.*timesfm.*详解.*对比",
          "timesfm.*深度解析.*对比测试",
          "timesfm详解和对比测试",
          "google timesfm explanation comparison",
          "时代变了.*预测.*大模型",
          "预测.*大模型.*timesfm",
          "timesfm 2.5.*深度解析",
          "谷歌.*timesfm2.*深度解析",
          "google timesfm 2.5 deep analysis",
          "日晷.*sundial.*高性能",
          "日晷.*sundial.*系列",
          "ai论文速读.*日晷",
          "sundial.*高性能.*时间序列",
          "sundial family highly capable",
          "icml 2025 oral sundial",
          "timer.*generative.*预训练",
          "timer.*大时序模型",
          "timer generative pretrained transformers",
          "large time series models icml 2024",
          "timer icml 2024 large time series",
          "openltm.*预训练.*代码",
          "openltm.*大时序模型",
          "openltm implementations pre-training",
          "large time series models pre-training",
          "openltm datasets code",
          "时序.*moe.*十亿.*预训练",
          "时序.*moe.*3000亿",
          "global first.*十亿.*预训练",
          "time-moe billion scale mixture experts",
          "time moe 300 billion time points",
          "time-moe paper page",
          "timefound.*超越.*时序",
          "timefound.*零样本.*泛化",
          "百度.*timefound.*超越",
          "timefound beyond timesfm zero shot",
          "baidu timefound time series foundation",
          "timepro.*多变量.*时序",
          "timepro.*攻克难题",
          "huawei noah timepro multivariate",
          "timepro攻克多变量时序预测世界难题",
          "timemixer.*可分解多尺度",
          "timemixer.*论文精读",
          "timemixer.*iclr 2024",
          "timemixer 论文精读 2024",
          "论文精读.*timemixer.*iclr",
          "timemixer iclr 2024 paper reading",
          "timemixer\+\+.*通用.*sota",
          "timemixer\+\+.*全面超越.*transformer",
          "timemixer plus plus general time series",
          "timekan.*kan.*时序",
          "timekan.*iclr 2025.*sota",
          "timekan kan-based frequency decomposition",
          "timekan iclr 2025",
          "上海ai lab.*timekan.*iclr 2025",
          "chebykan.*chebyshev.*kan",
          "chebykan.*kolmogorov-arnold",
          "chebykan kolmogorov arnold chebyshev",
          "kolmogorov-arnold networks chebyshev",
          "chebyshev polynomials instead b-splines",
          "semixer.*语义.*mlp-mixer",
          "semixer.*全面领先.*数据集",
          "semixer semantics enhanced mlp-mixer",
          "semixer www 2026",
          "终于不用改模型架构.*轻量mlp",
          "tats lightweight mlp time series",
          "tats boost existing time series models",
          "简单.*高效.*mscp.*时序",
          "mscp simple efficient time series forecasting",
          "mscp outperforms complex algorithms",
          "刷新.*interpdn.*新霸主",
          "interpdn.*干翻.*transformer",
          "interpdn time series forecasting sota",
          "interpdn beats transformer",
          "牛津.*p-slstm.*lstm.*潜力",
          "p-slstm lstm long-term forecasting",
          "p-slstm oxford lstm potential",
          "阿里.*fedformer.*长程.*超越",
          "fedformer long-range forecasting sota",
          "fedformer damo icml 2022",
          "倒置.*transformer.*时序",
          "itransformer inverted transformers",
          "itransformer iclr 2024 spotlight",
          "倒置transformer.*卓有成效",
          "干翻.*transformer.*interpdn",
          "时序.*频谱.*注意力",
          "spectral coherence attention time series",
          "频谱相干注意力.*时序",
          "时序.*双飞轮.*纯mlp",
          "dual flywheel mlp time series",
          "纯mlp.*性能效能.*时序",
          "时序.*冻结.*大语言模型.*适配器",
          "frozen llm time series adapter",
          "冻结llm.*时序适配器",
          "时序预测.*性能.*timemixer",
          "替代.*transformer.*频谱.*相干",
          "spectral attention replaces transformer",
          "频谱.*时序.*动态关系",
          "vlm.*时序.*视觉.*语言",
          "visual language model time series detection",
          "vlm.*时序.*检测.*难题",
          "时序.*可解释性.*26.*数据集",
          "timesliver interpretable time series 26",
          "timesliver 26 datasets sota",
          "时空联合建模.*时空可持续",
          "spatiotemporal joint modeling sustainable",
          "时空.*联合.*可持续.*学习",
          "时间序列.*外生.*变量.*辅助",
          "timexer exogenous variables transformers",
          "时间序列.*管弦乐.*集成.*框架",
          "tsorchestra ensemble zero-shot",
          "时间序列.*零样本.*集成",
          "d2vformer.*任意.*位置.*长度",
          "d2vformer arbitrary position length forecasting",
          "d2vformer 任意位置 任意长度",
          "贝叶斯优化.*lstm.*准确.*sota",
          "bayesian optimization lstm sota",
          "预测.*损失函数.*错误",
          "loss function forecasting wrong",
          "预测.*损失.*用错",
          "预测不准.*损失函数.*错误",
          "能源.*交易员.*预测.*七个月",
          "energy trader seven month forecast",
          "ai.*能源交易.*逐小时",
          "光伏发电.*baseline.*dcic",
          "dcic 2024 photovoltaic baseline",
          "datacenter.*计算管理.*规划",
          "power modeling datacenter compute",
          "kronos.*金融.*语言.*基础",
          "kronos language financial markets",
          "decoder-only.*时序.*基础",
          "decoder only foundation time series",
          "重塑.*评估.*task-driven.*基准",
          "time next generation benchmark",
          "时间序列.*评估.*新基准",
          "时间序列.*多模态.*llm",
          "time series multimodal llm",
          "2026时序.*多模态",
          "在工业时序.*llm.*歇菜",
          "llm fail industrial time series",
          "时序.*适配器.*llm.*外挂",
          "time series adapter frozen llm",
          "冻结.*大语言模型.*外挂.*适配器",
          "时间序列.*外生变量",
          "exogenous variable time series forecasting",
          "时间序列.*管弦乐.*零样本",
          "time series orchestra ensemble zero shot",
          "时间序列.*任意位置.*任意长度",
          "time series arbitrary position length",
          "预测.*损失函数",
          "forecasting loss function",
          "时序.*损失函数",
          "time series loss function",
          "能源.*ai.*预测",
          "energy ai forecasting",
          "光伏.*预测.*baseline",
          "pv forecasting baseline",
          "datacenter.*power.*compute",
          "金融.*基础模型",
          "financial foundation model",
          "decoder-only.*时间序列",
          "decoder only time series",
          "重塑.*评估.*基准",
          "reshape evaluation benchmark",
          "time.*新一代基准",
          "贝叶斯优化.*sota",
          "bayesian optimization sota",
          "时序.*多模态.*大模型",
          "2026.*时序.*新思路",
          # Time series other papers - broad match
          "informer.*算法",
          "informer.*aaai.*2021",
          "zhouhaoyi.*informer",
          "n-beats.*neural basis",
          "n-beats.*service.*now",
          "service.*now.*n-beats",
          "n-beats.*interpretable",
          "service now n-beats neural basis",
          "n-beats element ai",
          ]
    # 4. Data science / analysis tools
    ds = ["data science", "数据分析", "数据科学", "data analysis",
          "data viz", "pandas", "jupyter", "notebook", "marimo",
          "数据.*分析", "探索性数据分析", "exploratory data analysis",
          "改进探索性数据", "geostatsguy.*data science",
          "python.*data science", "interactive dashboard",
          "data label", "数据标注", "open source data label",
          "data labeling", "open source data labeling",
          "fiftyone", "discover fiftyone",
          "pdf.*translate", "pdf.*math", "pdfmath",
          "ffmpeg", "docker", "内网穿透", "natapp",
          "frp", "内网映射", "樱花.*内网",
          "stirling.*pdf", "pdf application",
          "openssh.*private key", "private key.*rsa",
          "handcalcs", "python.*calculation.*latex",
          "chebyshev polynomials.*wikipedia",
          "glmnet.*rdocumentation",
          "introduction to.*glmnet",
          "an introduction to glmnet",
          "basinhopping.*scipy",
          "scipy.*basinhopping",
          "optimize.*scipy",
          "bayesian optimization.*package",
          "basic tour.*bayesian",
          "bayesian.*optimization.*package",
          "api reference.*simple-pid",
          "simple-pid.*api",
          "pid.*控制",
          "什么是pid",
          "what is pid",
          "api.*opennmt",
          "quickstart.*opennmt",
          "gurobi help center",
          "gurobi optimization",
          "gurobi modeling examples",
          "gurobi.*getting started",
          "getting started.*gurobi",
          "clarabel.*interior-point",
          "clarabel.*rust",
          "clarabel.rs",
          "oxfordcontrol.*clarabel",
          "convex optimization.*boyd",
          "boyd.*vandenberghe",
          "alphaopt.*大模型.*优化",
          "alphaopt.*经验知识库",
          "llm.*or.*优化",
          "llm.*or.*杉数",
          "alphaopt 大模型 优化建模",
          "llm or 杉数科技",
          "为什么这个线性规划不用求解器",
          "连续背包.*贪心",
          "linear programming.*solver",
          "continuous knapsack.*greedy",
          "学习资料.*优化算法",
          "doFighter.*computational intelligence",
          "计算智能.*优化算法",
          "计算智能.*启发式",
          "convex optimization.*convex conic",
          "convex conic optimisation",
          "clarabel interior point solver",
          "gurobi help.*center",
          "gurobi modeling.*examples",
          "getting started gurobi optimizer",
          "decision intelligence",
          "decision intelligence technology",
          "优化.*算法.*工程",
          "optimization.*algorithm.*engineering",
          ]
    # 5. Math / stats
    math = ["pca", "principal component", "主成分分析",
            "降维", "dimensionality reduction",
            "statistics", "统计", "概率", "probability",
            "chebyshev", "傅里叶", "fourier",
            "线性规划", "linear programming",
            "贪心", "greedy", "背包", "knapsack",
            "凸优化", "convex optimization",
            "内点法", "interior point",
            "glmnet", "lasso.*回归",
            "岭回归", "ridge regression",
            "ardl", "autoregressive distributed lag",
            "panel ardl",
            "一篇深入剖析pca",
            "主成分分析.*原理",
            "pca.*原理总结",
            "pca.*sklearn",
            "降维.*pca",
            "machine learning.*pca",
            "主成分.*降维",
            "pca详解",
            "pca实战",
            "hotelling.*t-squared",
            "scree plot",
            "eigenvalue.*eigenvector",
            "协方差矩阵",
            "covariance matrix",
            "方差.*贡献率",
            "variance contribution",
            ]
    # 6. Other
    other_default = True

    for k in dl:
        if re.search(k, n):
            return "1. 深度学习基础教程"
    for k in llm:
        if re.search(k, n):
            return "2. LLM架构与多模态"
    for k in ts:
        if re.search(k, n):
            return "3. 时间序列其他论文"
    for k in ds:
        if re.search(k, n):
            return "4. 数据科学/分析工具"
    for k in math:
        if re.search(k, n):
            return "5. 数学/统计基础"
    return "6. 其他未分类"

for f in remaining:
    cat = classify(f)
    cats[cat].append(f)

for cat, files in cats.items():
    print(f"\n{'='*60}")
    print(f"{cat} ({len(files)} files)")
    print(f"{'='*60}")
    for f in files:
        print(f"  - {f}")

print(f"\n\nTotal remaining: {len(remaining)}")
for cat, files in cats.items():
    print(f"  {cat}: {len(files)}")
